import { useSession, signIn, signOut } from "next-auth/react";
import Head from "next/head";

export default function Home() {
  const { data: session, status } = useSession();
  console.log(session, status);

  return (
    <div className="mx-auto max-w-7xl sm:px-6 lg:px-8">
      <Head>
        <title>
          {session ? `Welcome ${session.user.name}` : "Welcome back"}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {status === "loading" ? (
        <p>Loading..</p>
      ) : (
        <div className="md:flex md:items-center md:justify-between py-8">
          <div className="min-w-0 flex-1">
            <h2 className="text-2xl font-bold leading-7 text-dark sm:truncate sm:text-3xl sm:tracking-tight">
              {session ? <p>Welcome {session.user.name}</p> : "Welcome back"}
            </h2>
          </div>
          <div className="mt-4 flex md:mt-0 md:ml-4">
            {session ? (
              <button
                onClick={() => signOut()}
                type="button"
                className="inline-flex items-center rounded-md border border-transparent bg-gray-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:ring-offset-gray-800"
              >
                Logout
              </button>
            ) : (
              <button
                onClick={() => signIn()}
                type="button"
                className="ml-3 inline-flex items-center rounded-md border border-transparent bg-indigo-500 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-600 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:ring-offset-gray-800"
              >
                Sign in
              </button>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
